import { Inter } from "next/font/google";
import "./globals.css";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import MainProvider from "@/app/MainProvider";

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Quick Search",
//   description: "Generated by create next app",
// };

export const metadata = {
  title: "Quick Search",
  description: "Find an apartment, condo, office space, house, and lot for sale or for rent in top locations.",
  openGraph: {
    title: "Quick Search",
    description: "Find an apartment, condo, office space, house, and lot for sale or for rent in top locations.",
    images: [
      {
        url: "/logo.webp",
        width: 800,                    
        height: 600,                  
        alt: "Quick Search Image",       
      },
    ],
  },
};


export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
          <MainProvider>{children}</MainProvider>
          <ToastContainer />
      </body>
    </html>
  );
}
