export const divisions = [
  {
    label: "Chattagram - চট্টগ্রাম",
    value: "chattagram",
    districts: [
      { label: "Comilla - কুমিল্লা", value: "comilla" },
      { label: "Feni - ফেনী", value: "feni" },
      { label: "Brahmanbaria - ব্রাহ্মণবাড়িয়া", value: "brahmanbaria" },
      { label: "Rangamati - রাঙ্গামাটি", value: "rangamati" },
      { label: "Noakhali - নোয়াখালী", value: "noakhali" },
      { label: "Chandpur - চাঁদপুর", value: "chandpur" },
      { label: "Lakshmipur - লক্ষ্মীপুর", value: "lakshmipur" },
      { label: "Chattogram - চট্টগ্রাম", value: "chattogram" },
      { label: "Coxsbazar - কক্সবাজার", value: "coxsbazar" },
      { label: "Khagrachhari - খাগড়াছড়ি", value: "khagrachhari" },
      { label: "Bandarban - বান্দরবান", value: "bandarban" },
    ],
  },
  {
    label: "Rajshahi - রাজশাহী",
    value: "rajshahi",
    districts: [
      { label: "Sirajganj - সিরাজগঞ্জ", value: "sirajganj" },
      { label: "Pabna - পাবনা", value: "pabna" },
      { label: "Bogura - বগুড়া", value: "bogura" },
      { label: "Rajshahi - রাজশাহী", value: "rajshahi" },
      { label: "Natore - নাটোর", value: "natore" },
      { label: "Joypurhat - জয়পুরহাট", value: "joypurhat" },
      { label: "Chapainawabganj - চাঁপাইনবাবগঞ্জ", value: "chapainawabganj" },
      { label: "Naogaon - নওগাঁ", value: "naogaon" },
    ],
  },
  {
    label: "Khulna - খুলনা",
    value: "khulna",
    districts: [
      { label: "Jashore - যশোর", value: "jashore" },
      { label: "Satkhira - সাতক্ষীরা", value: "satkhira" },
      { label: "Meherpur - মেহেরপুর", value: "meherpur" },
      { label: "Narail - নড়াইল", value: "narail" },
      { label: "Chuadanga - চুয়াডাঙ্গা", value: "chuadanga" },
      { label: "Kushtia - কুষ্টিয়া", value: "kushtia" },
      { label: "Magura - মাগুরা", value: "magura" },
      { label: "Khulna - খুলনা", value: "khulna" },
      { label: "Bagerhat - বাগেরহাট", value: "bagerhat" },
      { label: "Jhenaidah - ঝিনাইদহ", value: "jhenaidah" },
    ],
  },
  {
    label: "Barisal - বরিশাল",
    value: "barisal",
    districts: [
      { label: "Jhalakathi - ঝালকাঠি", value: "jhalakathi" },
      { label: "Patuakhali - পটুয়াখালী", value: "patuakhali" },
      { label: "Pirojpur - পিরোজপুর", value: "pirojpur" },
      { label: "Barisal - ভোলা", value: "barisal" },
      { label: "Bhola - পিরোজপুর", value: "bhola" },
      { label: "Barguna - বরগুনা", value: "barguna" },
    ],
  },
  {
    label: "Sylhet - সিলেট",
    value: "sylhet",
    districts: [
      { label: "Sylhet - সিলেট", value: "sylhet" },
      { label: "Moulvibazar - মৌলভীবাজার", value: "moulvibazar" },
      { label: "Habiganj - হবিগঞ্জ", value: "habiganj" },
      { label: "Sunamganj - সুনামগঞ্জ", value: "sunamganj" },
    ],
  },
  {
    label: "Dhaka - ঢাকা",
    value: "dhaka",
    districts: [
      { label: "Narsingdi - নরসিংদী", value: "narsingdi" },
      { label: "Gazipur - গাজীপুর", value: "gazipur" },
      { label: "Shariatpur - শরীয়তপুর", value: "shariatpur" },
      { label: "Narayanganj - নারায়ণগঞ্জ", value: "narayanganj" },
      { label: "Tangail - টাঙ্গাইল", value: "tangail" },
      { label: "Kishoreganj - কিশোরগঞ্জ", value: "kishoreganj" },
      { label: "Manikganj - মানিকগঞ্জ", value: "manikganj" },
      { label: "Dhaka - ঢাকা", value: "dhaka" },
      { label: "Munshiganj - মুন্সিগঞ্জ", value: "munshiganj" },
      { label: "Rajbari - রাজবাড়ী", value: "rajbari" },
      { label: "Madaripur - মাদারীপুর", value: "madaripur" },
      { label: "Gopalganj - গোপালগঞ্জ", value: "gopalganj" },
      { label: "Faridpur - ফরিদপুর", value: "faridpur" },
    ],
  },
  {
    label: "Rangpur - রংপুর",
    value: "rangpur",
    districts: [
      { label: "Panchagarh - পঞ্চগড়", value: "panchagarh" },
      { label: "Dinajpur - দিনাজপুর", value: "dinajpur" },
      { label: "Lalmonirhat - লালমনিরহাট", value: "lalmonirhat" },
      { label: "Nilphamari - নীলফামারী", value: "nilphamari" },
      { label: "Gaibandha - গাইবান্ধা", value: "gaibandha" },
      { label: "Thakurgaon - ঠাকুরগাঁও", value: "thakurgaon" },
      { label: "Rangpur - রংপুর", value: "rangpur" },
      { label: "Kurigram - কুড়িগ্রাম", value: "kurigram" },
    ],
  },
  {
    label: "Mymensingh - ময়মনসিংহ",
    value: "mymensingh",
    districts: [
      { label: "Sherpur - শেরপুর", value: "sherpur" },
      { label: "Mymensingh - ময়মনসিংহ", value: "mymensingh" },
      { label: "Jamalpur - জামালপুর", value: "jamalpur" },
      { label: "Netrokona - নেত্রকোণা", value: "netrokona" },
    ],
  },
];
